### ISSUE TITLE
Issue Error: Invalid call to createOffer

### ISSUE THREAD

**Issue by jaricek** [cjb/serverless-webrtc#23]
Hi,
I have this issue:
root@vm3:~/node_modules/serverless-webrtc# node serverless-webrtc.js --create

/home/jaricek/node_modules/wrtc/lib/peerconnection.js:215
      throw new Error('Invalid call to createOffer - function must either have
            ^
Error: Invalid call to createOffer - function must either have prototype ([config]) or (successCallback, failureCallback, [config]).
    at RTCPeerConnection.createOffer (/home/jaricek/node_modules/wrtc/lib/peerconnection.js:215:13)
    at makeOffer (/home/jaricek/node_modules/serverless-webrtc/serverless-webrtc.js:145:6)
    at Object.<anonymous> (/home/jaricek/node_modules/serverless-webrtc/serverless-webrtc.js:41:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
root@vm3:~/node_modules/serverless-webrtc#

Any idea have I can fix it ? thx

**Comment by jaricek** [comment]
OK, fixed there was problem with version of wrtc.

**Comment by kruherson1337** [comment]
What was the problem with version, I am getting same error? 

I try using 

"wrtc": "~0.0.29"
and
"wrtc": "0.0.61"

and with no luck, to get it working

**Comment by lempere** [comment]
@kruherson1337  check this https://github.com/cjb/serverless-webrtc/pull/27

**Comment by Zibri** [comment]
same problem here any solutions?
