### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by uyouthe** [cjb/serverless-webrtc#30]
Hello! The idea itself is awesome, but when I try to establish a connection, I got this:
```
Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDivElement.trigger (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:4773:11)
    at Object.trigger (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:4502:60)
    at HTMLDivElement.<anonymous> (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:5055:17)
    at Function.each (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:590:23)
    at init.each (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:237:17)
    at init.trigger (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:5054:15)
    at init.jQuery.fn.(anonymous function) [as focus] (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:6657:9)
    at HTMLDocument.<anonymous> (https://cjb.github.io/serverless-webrtc/js/bootstrap.js:910:27)
    at HTMLDocument.dispatch (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:4618:9)
    at HTMLDocument.elemData.handle (https://cjb.github.io/serverless-webrtc/js/jquery-2.0.0.js:4302:28)
```
I'm trying to connect my phone (Meizu m3s, Android, latest Chrome) and my PC (Windows, latest Chrome). Both are connected to same wifi network. It doesn't matter if it's a local file or hosted page, the error appears anyway.

**Comment by xem** [comment]
Hi, here's a simplified remake of this project, probably more stable : https://github.com/xem/miniWebRTC
Could you test it? :)

**Comment by pachacamac** [comment]
@xem I have the same issue as @uyouthe in up to date Chromium. Tested https://github.com/xem/miniWebRTC and it worked.

**Comment by xem** [comment]
so all is fine in my version? (miniWebrtc)

**Comment by pachacamac** [comment]
Yes seems so. It's a bit inconvenient to handle but works just fine once you figured out where to past what when :)
